config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :appeals
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :subscribers
  resources :comments

  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  root 'posts#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'about/index', to: 'about#index'
  get 'promo/index', to: 'promo#index'
  get 'posts/index', to: 'posts#index'
  get 'comments/index', to: 'comments#index'
  get 'appeals/index', to: 'appeals#index'
  get 'egg_article/index', to: 'egg_article#index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appeal.rb
class Appeal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :section, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		mount_uploader :image, ImageUploader
		validates :name, :presence => true

    has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category
		belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :posts, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.favorited_posts
      render actions: :show
      @favorites = @user.favorites.all
    else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end

  def favorited?(post)
    favorites.find_by(post_id: post.id).present?
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/appeals_helper.rb
module AppealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/egg_article_helper.rb
module EggArticleHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="search">
  <input type="text" name="Поиск" value="Поиск">
  <%= image_tag "search.svg"%>
</div>

<% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="top_menu">
      <%= image_tag "logo.svg", :class =>"logo_topmenu"%>
    <div class="menu_topmenu">
      <%= link_to 'Статьи', posts_path %>
      <%= link_to 'Подборки', categories_path %>
      <%= link_to 'Комментарии', comments_path %>
      <%= link_to 'Пользователи', users_path %>
      <%= link_to 'Обращения', appeals_path %>
    </div>
    <div class="bottom_topmenu">
      <% if user_signed_in? %>
        <%= link_to 'Аккаунт', current_user %>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Авторизация', new_user_session_path %>
        <%= link_to 'Регистрация', new_user_registration_path %>
      <% end %>
    </div>
    </div>


<div class="sort">
  <p>Сортировать по:</p>
  <a href="#">Имени</a>
  <a href="#">Никнейму</a>
  <a href="#">Логину</a>
</div>

<table class="table">
  <thead class="thead">
    <tr class="tr_top tr_top_users">
      <td style="grid-area: point1;">Имя</td>
      <td style="grid-area: point2">Фамилия</td>
      <td style="grid-area: point3">Никнейм</td>
      <td style="grid-area: point4">Логин</td>
      <td  style="grid-area: point5">Действие</td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="tr_bottom tr_bottom_users">
        <td style="grid-area: point1"><%= user.name %></td>
        <td style="grid-area: point2"><%= user.surname %></td>
        <td style="grid-area: point3"><%= user.username %></td>
        <td style="grid-area: point4"><%= link_to user.email, user %></td>
        <td class="edit_destroy" style="grid-area: point5">
          <% if user_signed_in? && current_user.isadmin == true %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"destroy_button" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>ID <%= @user.id %></p>
<p>Email <%= @user.email %></p>
<p>Username <%= @user.username %></p>
<% if user_signed_in? && current_user.isadmin == true %>
  <p>Admin <%= @user.isadmin %></p>
<% end %>

In favorites <%= @user.favorites.count %> <%= (@user.favorites.count) == 1 ? 'Post' : 'Posts'%>
<% @posts.each do |post| %>
  <br><%= link_to post.title, post %>
<% end %>

<% if user_signed_in? && @user.id == current_user.id %>
	<p><%= link_to 'Edit profile', edit_user_registration_path %></p>
<% end %>