config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :appeals
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :subscribers
  resources :comments

  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  root 'posts#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'about/index', to: 'about#index'
  get 'promo/index', to: 'promo#index'
  get 'posts/index', to: 'posts#index'
  get 'comments/index', to: 'comments#index'
  get 'appeals/index', to: 'appeals#index'
  get 'egg_article/index', to: 'egg_article#index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appeal.rb
class Appeal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :section, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		mount_uploader :image, ImageUploader
		validates :name, :presence => true

    has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category
		belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :posts, dependent: :destroy
end

app/controllers/appeals_controller.rb
class AppealsController < ApplicationController
  before_action :set_appeal, only: %i[ show edit update destroy ]

  # GET /appeals or /appeals.json
  def index
    @appeals = Appeal.all
  end

  # GET /appeals/1 or /appeals/1.json
  def show
  end

  # GET /appeals/new
  def new
    @appeal = Appeal.new
  end

  # GET /appeals/1/edit
  def edit
  end

  # POST /appeals or /appeals.json
  def create
    @appeal = Appeal.new(appeal_params)

    respond_to do |format|
      if @appeal.save
        format.html { redirect_to @appeal, notice: "Appeal was successfully created." }
        format.json { render :show, status: :created, location: @appeal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appeals/1 or /appeals/1.json
  def update
    respond_to do |format|
      if @appeal.update(appeal_params)
        format.html { redirect_to @appeal, notice: "Appeal was successfully updated." }
        format.json { render :show, status: :ok, location: @appeal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appeal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appeals/1 or /appeals/1.json
  def destroy
    @appeal.destroy
    respond_to do |format|
      format.html { redirect_to appeals_url, notice: "Appeal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appeal
      @appeal = Appeal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appeal_params
      params.require(:appeal).permit(:author, :email, :content, :data)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/appeals_helper.rb
module AppealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/egg_article_helper.rb
module EggArticleHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appeals/_form.html.erb
<%= form_with(model: appeal) do |form| %>
  <% if appeal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appeal.errors.count, "error") %> prohibited this appeal from being saved:</h2>

      <ul>
        <% appeal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_select :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appeals/edit.html.erb
<h1>Editing Appeal</h1>

<%= render 'form', appeal: @appeal %>

<%= link_to 'Show', @appeal %> |
<%= link_to 'Back', appeals_path %>

app/views/appeals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="search">
  <input type="text" name="Поиск" value="Поиск">
  <%= image_tag "search.svg"%>
</div>

<% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="top_menu">
      <%= image_tag "logo.svg", :class =>"logo_topmenu"%>
    <div class="menu_topmenu">
      <%= link_to 'Статьи', posts_path %>
      <%= link_to 'Подборки', categories_path %>
      <%= link_to 'Комментарии', comments_path %>
      <%= link_to 'Пользователи', users_path %>
      <%= link_to 'Обращения', appeals_path %>
    </div>
    <div class="bottom_topmenu">
      <% if user_signed_in? %>
        <%= link_to 'Аккаунт', current_user %>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Авторизация', new_user_session_path %>
        <%= link_to 'Регистрация', new_user_registration_path %>
      <% end %>
    </div>
    </div>


<div class="appeal_status">
  <a href="#">Все</a>
  <a href="#">Открытые</a>
  <a href="#">Закрытые</a>
  <a href="#">Неликвидные</a>
</div>

<div class="sort">
  <p>Сортировать по:</p>
  <a href="#">Имени</a>
  <a href="#">Почте</a>
  <a href="#">Дате</a>
</div>

<table class="table">
  <thead class="thead">
    <tr class="tr_top tr_top_appeals">
      <td style="grid-area: point1;">Отправитель</td>
      <td style="grid-area: point2;">Почта</td>
      <td style="grid-area: point3;">Содержание</td>
      <td style="grid-area: point4;">Дата</td>
      <td style="grid-area: point5;">Действие</td>
    </tr>
  </thead>

  <tbody>
    <% @appeals.each do |appeal| %>
      <tr class="tr_bottom tr_bottom_appeals">
        <td class="appeal_element" style="grid-area: point1;"><%= appeal.author %></td>
        <td class="appeal_element" style="grid-area: point2;"><%= appeal.email %></td>
        <td class="appeal_content" style="grid-area: point3;"><%= appeal.content %></td>
        <td class="appeal_element" style="grid-area: point4;"><%= time_ago_in_words(appeal.created_at)%></td>

        <td class="appeal_element" style="grid-area: point5;" class="show_edit_destroy">
          <%= link_to 'Show', appeal %>
          <%= link_to 'Edit', edit_appeal_path(appeal) %>
          <%= link_to 'Destroy', appeal, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <div class="new_smth">
  <%= image_tag "plus_sign.svg"%>
  <%= link_to 'Создать пост', new_appeal_path %>
</div> -->

app/views/appeals/new.html.erb
<h1>New Appeal</h1>

<%= render 'form', appeal: @appeal %>

<%= link_to 'Back', appeals_path %>

app/views/appeals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @appeal.author %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appeal.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @appeal.content %>
</p>

<p>
  <strong>Data:</strong>
  <%= @appeal.data %>
</p>

<%= link_to 'Edit', edit_appeal_path(@appeal) %> |
<%= link_to 'Back', appeals_path %>