config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :appeals
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :subscribers
  resources :comments

  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  root 'posts#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'about/index', to: 'about#index'
  get 'promo/index', to: 'promo#index'
  get 'posts/index', to: 'posts#index'
  get 'comments/index', to: 'comments#index'
  get 'appeals/index', to: 'appeals#index'
  get 'egg_article/index', to: 'egg_article#index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appeal.rb
class Appeal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :section, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		mount_uploader :image, ImageUploader
		validates :name, :presence => true

    has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category
		belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :posts, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :author, :content, :image, :category_id, :section_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/appeals_helper.rb
module AppealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/egg_article_helper.rb
module EggArticleHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="whole_form">
  <div class="name_form">
    <%= form.label :name, "Название" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :section_id, "Раздел" %>
    <%= form.select :section_id, Section.pluck(:name, :id) %>
  </div>

  <div class="field">
    <%= form.label :category_id, "Подборка" %>
    <%= form.select :category_id, Category.pluck(:name, :id) %>
  </div>

  <div class="image_form">
    <%= form.label :image, "Фотография" %>
    <%= form.file_field :image %>
  </div>

  <div class="content_form">
    <%= form.label :content, "Текст" %>
    <%= form.cktext_area :content %>
  </div>

  <div class="actions_form">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="header_second_row">
  <td><%= link_to image_tag('arrow_back.svg'), posts_path %></td>
  <%= link_to 'Назад', posts_path%>
</div>

<div class="header">
  <h1>Редактирование статьи</h1>
</div>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="top_menu">
      <%= image_tag "logo.svg", :class =>"logo_topmenu"%>
    <div class="menu_topmenu">
      <%= link_to 'Статьи', posts_path %>
      <%= link_to 'Подборки', categories_path %>
      <%= link_to 'Комментарии', comments_path %>
      <%= link_to 'Пользователи', users_path %>
      <%= link_to 'Обращения', appeals_path %>
    </div>
    <div class="bottom_topmenu">
      <% if user_signed_in? %>
        <%= link_to 'Аккаунт', current_user %>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Авторизация', new_user_session_path %>
        <%= link_to 'Регистрация', new_user_registration_path %>
      <% end %>
    </div>
    </div>

<div class="search">
  <input type="text" name="Поиск" value="Поиск">
  <%= image_tag "search.svg"%>
</div>

<div class="post_status">
  <a href="#">Опубликованные</a>
  <a href="#">Черновики</a>
</div>

<div class="sort">
  <p>Сортировать по:</p>
  <a href="#">Названию</a>
  <a href="#">Дате</a>
  <a href="#">Разделу</a>
  <a href="#">Подборке</a>
  <a href="#">Автору</a>
</div>

<table class="table">
  <thead class="thead">
    <tr class="tr_top tr_top_posts">
			<td style="grid-area: point1;">Название</td>
      <td style="grid-area: point2">Раздел</td>
      <td style="grid-area: point3">Подборки</td>
      <td style="grid-area: point4">Автор</td>
      <td style="grid-area: point5">Дата</td>
			<td style="grid-area: point6">Действие</td>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="tr_bottom tr_bottom_posts">
        <td style="grid-area: point1"><%= post.name%></td>
        <td style="grid-area: point2"><%= post.section.name%></td>
        <td style="grid-area: point3"><%= post.category.name%></td>
        <td style="grid-area: point4"><%= post.author%></td>
        <td style="grid-area: point5"><%= time_ago_in_words(post.created_at)%></td>

        <td style="grid-area: point6" class="show_edit_destroy">
          <%= link_to 'Show', post, :class =>"show_button" %>
          <% if user_signed_in? && current_user.isadmin == true %>
            <%= link_to 'Edit', edit_post_path(post), :class =>"edit_button" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"destroy_button" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="new_smth">
  <%= image_tag "plus_sign.svg"%>
  <%= link_to 'Создать пост', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="header_second_row">
  <td><%= link_to image_tag('arrow_back.svg'), posts_path %></td>
  <%= link_to 'Назад', posts_path%>
</div>

<div class="header">
  <h1>Создание статьи</h1>
</div>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header_article">
  <div class="search_and_bttn"> 
    <input type="text" name="Поиск" placeholder="Хочу найти…">
    <div class="user_acc">
      <% if user_signed_in? %>
        <%= link_to image_tag('AccountMobile.svg'), current_user %>
      <% else %>
        <%= link_to image_tag('SignInMobile.svg'), new_user_registration_path %>
      <% end %>
    </div> 
  </div>
  <div class="mobile_menu">
    <a href="" class="main">Главная</a>
    <a href="">Продукты</a>
    <a href="">Витамины</a>
  </div>
</div>
<div class="whole_show">
  <div class="PostNameAndF">
    <h1><%= @post.name%></h1>
      <% if user_signed_in? %>
        <% pre_favorite = @post.favorites.find { |favorite| favorite.user_id == current_user.id} %>
        <% if pre_favorite %>
            <%= link_to image_tag('fIconActive.svg'), post_favorite_path(@post, pre_favorite), method: :delete %>
        <% else %>
            <%= link_to image_tag('fIconNone.svg'), post_favorites_path(@post), method: :post %>
        <% end %>
      <% end %>
  </div>
      <div class="show_image">
      	<%= image_tag(@post.image.url, alt: '') if @post.image?%>
      </div>
      <div class="article_content">
        <%= @post.content.html_safe %><br>
      </div>
      
      <div class="LikePart">
        <% if user_signed_in? %>
          <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= link_to image_tag('LikeIconActive.svg'), post_like_path(@post, pre_like), method: :delete %>
          <% else %>
            <%= link_to image_tag('LikeIconNone.svg'), post_likes_path(@post), method: :post %>
          <% end %>
        <% end %>
        <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? '' : ''%></p>
      </div>
      <hr>
        
        <%= render @post.comments %>
      <div class="please_reg">
        <h2 class="show_add_comment">Добавить комментарий</h2>
        <% if user_signed_in? %>
        <%= render "comments/form" %>
        <% else %>
        <p>Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to comment.</p>
        <% end %>
      </div>
        <div class="footerGlobal">
         <div class="footer"> 
              <%= image_tag("LogoFooter.svg")%>
              <div class="FooterInfo">
                <p>B8project@mail.ru</p>
                <div class="social">
                <a href="">vk</a>
                <a href="">telegram</a>
                <a href="">youtube</a>
                </div>
              </div>
          </div>
          <hr>
          <p>Электронная энциклопедия со статьями и подборками про продукты и витамины</p>
          <p class="year">©2022 B8</p>
        </div>


</div>