config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :appeals
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :subscribers
  resources :comments

  resources :posts do
      resources :comments
      resources :likes
      resources :favorites
  end

  root 'posts#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'about/index', to: 'about#index'
  get 'promo/index', to: 'promo#index'
  get 'posts/index', to: 'posts#index'
  get 'comments/index', to: 'comments#index'
  get 'appeals/index', to: 'appeals#index'
  get 'egg_article/index', to: 'egg_article#index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appeal.rb
class Appeal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :section, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		mount_uploader :image, ImageUploader
		validates :name, :presence => true

    has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category
		belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :posts, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :display_in_navbar, :author)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/appeals_helper.rb
module AppealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/egg_article_helper.rb
module EggArticleHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="whole_form">
  <div class="name_form">
    <%= form.label :name, "Название" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :section_id, "Раздел" %>
    <%= form.select :section_id, Section.pluck(:name, :id) %>
  </div>

  <div class="field">
    <%= form.label :description, "Описание" %>
    <%= form.cktext_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/categories/edit.html.erb
<div class="header_second_row">
  <td><%= link_to image_tag('arrow_back.svg'), categories_path%></td>
  <%= link_to 'Назад', categories_path%>
</div>

<div class="header">
  <h1>Редактирование подборки</h1>
</div>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="search">
  <input type="text" name="Поиск" value="Поиск">
  <%= image_tag "search.svg"%>
</div>

<% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="top_menu">
      <%= image_tag "logo.svg", :class =>"logo_topmenu"%>
    <div class="menu_topmenu">
      <%= link_to 'Статьи', posts_path %>
      <%= link_to 'Подборки', categories_path %>
      <%= link_to 'Комментарии', comments_path %>
      <%= link_to 'Пользователи', users_path %>
      <%= link_to 'Обращения', appeals_path %>
    </div>
    <div class="bottom_topmenu">
      <% if user_signed_in? %>
        <%= link_to 'Аккаунт', current_user %>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Авторизация', new_user_session_path %>
        <%= link_to 'Регистрация', new_user_registration_path %>
      <% end %>
    </div>
    </div>


<div class="sort">
  <p>Сортировать по:</p>
  <a href="#">Названию</a>
  <a href="#">Разделу</a>
  <a href="#">Автору</a>
</div>

<table class="table">
  <thead class="thead">
    <tr class="tr_top tr_top_categories">
      <td style="grid-area: point1;">Название</td>
      <td style="grid-area: point2">Раздел</td>
      <td style="grid-area: point3">Автор</td>
      <td style="grid-area: point4">Действие</td>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr class="tr_bottom tr_bottom_categories">
        <td style="grid-area: point1"><%= category.name%></td>
        <td style="grid-area: point3"><%= category.author%></td>

        <td class="edit_destroy" style="grid-area: point4">
          <% if user_signed_in? && current_user.isadmin == true %>
            <%= link_to 'Edit', edit_category_path(category), :class =>"edit_button" %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"destroy_button" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="new_smth">
  <%= image_tag "plus_sign.svg"%>
  <%= link_to 'Создать подборку', new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="header_second_row">
  <td><%= link_to image_tag('arrow_back.svg'), posts_path %></td>
  <%= link_to 'Назад', posts_path%>
</div>

<div class="header">
  <h1>Создание подборки</h1>
</div>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header_second_row">
  <td><%= link_to image_tag('arrow_back.svg'), category_path%></td>
  <%= link_to 'Назад', category_path%>
</div>

<div class="header">
  <h1><%= @category.name%></h1>
</div>

<div class="whole_show_category">
    

        <strong>Описание</strong><br>
        <%= @category.description%><br>
</div>